// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaphiwE5VOvEFLZVo3V2J4kP6Fq0PFuks',
    appId: '1:173785156871:web:3b472224ce4c6f7b8549a2',
    messagingSenderId: '173785156871',
    projectId: 'appflutter-ffe43',
    authDomain: 'appflutter-ffe43.firebaseapp.com',
    storageBucket: 'appflutter-ffe43.firebasestorage.app',
    measurementId: 'G-WSFWE3FDE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJ83RUsBOH2Z2zc0oNgUnhbhYuBzNdvU',
    appId: '1:173785156871:android:f6944bf7cdb3e4888549a2',
    messagingSenderId: '173785156871',
    projectId: 'appflutter-ffe43',
    storageBucket: 'appflutter-ffe43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZcXlaSBIvmydSy3Wr7KBArjMqgloiJik',
    appId: '1:173785156871:ios:4e14c3052e42e05a8549a2',
    messagingSenderId: '173785156871',
    projectId: 'appflutter-ffe43',
    storageBucket: 'appflutter-ffe43.firebasestorage.app',
    iosBundleId: 'com.example.tpFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZcXlaSBIvmydSy3Wr7KBArjMqgloiJik',
    appId: '1:173785156871:ios:4e14c3052e42e05a8549a2',
    messagingSenderId: '173785156871',
    projectId: 'appflutter-ffe43',
    storageBucket: 'appflutter-ffe43.firebasestorage.app',
    iosBundleId: 'com.example.tpFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaphiwE5VOvEFLZVo3V2J4kP6Fq0PFuks',
    appId: '1:173785156871:web:4861f1693d18d19e8549a2',
    messagingSenderId: '173785156871',
    projectId: 'appflutter-ffe43',
    authDomain: 'appflutter-ffe43.firebaseapp.com',
    storageBucket: 'appflutter-ffe43.firebasestorage.app',
    measurementId: 'G-3QN51GV9HF',
  );
}
